import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import initTranslations from "../i18n";
import TranslationsProvider from "@/components/TranslationProvider";
import i18nConfig from "@/i18n.config";
import Button from "@/components/Button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "profile",
  description: "Generated by create next app",
};

const i18nNamespaces = [
  "sidebar",
  "Form",
  "navbar",
  "profileCard",
  "Statistics",
];
export default async function RootLayout({ children, params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);
  const direction = i18nConfig.dir[locale] || "ltr"; // Default to 'ltr'

  return (
    <html lang={locale} dir={direction}>
      <body className="flex">
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <div
            className={`${
              direction === "rtl"
                ? "right-0 fixed   z-50 sidebar bg-white hidden md:block top-0  h-screen w-[280px]"
                : " left-0 fixed   z-50 sidebar bg-white hidden md:block  top-0  h-screen w-[280px]"
            }`}
          >
            <Sidebar direction={direction} />
          </div>

          <div
            className={`${
              direction === "rtl"
                ? "md:mr-[280px] flex-grow"
                : "md:ml-[280px] flex-grow"
            }`}
          >
            <div className="md:hidden block  ">
              <Button direction={direction} />
            </div>

            {children}
          </div>
        </TranslationsProvider>
      </body>
    </html>
  );
}
